version:  "3.7"
services:
  postgres:
    image: postgres:11-alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment: # The following sets up a db by default
      POSTGRES_DB: consent
      POSTGRES_USER: consent
      POSTGRES_PASSWORD: <db pass>
  mysql:
    image: mysql:5.6
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - ./<conset db name>:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: <root password>
      MYSQL_DATABASE: consent
      MYSQL_USER: consent
      MYSQL_PASSWORD: <db pass>
