version:  "3.7"
services:
  postgres:
    image: postgres:9.6.5
    container_name: postgres
    ports:
      - 5432:5432
    environment: # The following sets up a db by default
      POSTGRES_PASSWORD: <root password>
      POSTGRES_USER: <root user>
      POSTGRES_DB: consent
  mysql:
    image: mysql:5.6
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - ./<conset db name>:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: <password>
      MYSQL_DATABASE: consent
      MYSQL_USER: <db user>
      MYSQL_PASSWORD: <db pass>
