version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
    target-branch: develop
    reviewers:
      - "@DataBiosphere/DUOS"
    commit-message:
      prefix: "[DUOS-1740-actions]"
    groups:
      action-dependencies:
        patterns:
          - "*"
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    target-branch: develop
    reviewers:
      - "@DataBiosphere/DUOS"
    labels:
      - dependency
    commit-message:
      prefix: "[DUOS-1740-maven]"
    groups:
      maven-dependencies:
        patterns:
          - "*"
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    target-branch: develop
    reviewers:
      - "@DataBiosphere/DUOS"
    labels:
      - dependency
    commit-message:
      prefix: "[DUOS-1740-docker]"
    groups:
      docker-dependencies:
        patterns:
          - "*"
