version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    target-branch: develop
    reviewers:
      - "@DataBiosphere/DUOS"
    labels:
      - dependency
    commit-message:
      prefix: "[DUOS-1740-dependabot]"
    groups:
      maven-dependencies:
        patterns: "*"
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    target-branch: develop
    reviewers:
      - "@DataBiosphere/DUOS"
    labels:
      - dependency
    commit-message:
      prefix: "[DUOS-1740-dependabot]"
    groups:
      docker-dependencies:
        patterns: "*"
