version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    target-branch: develop
    commit-message:
      prefix: "[DCJ-308-actions]"
    groups:
      action-dependencies:
        patterns:
          - "*"
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    target-branch: develop
    labels:
      - dependency
    commit-message:
      prefix: "[DCJ-308-maven]"
    groups:
      maven-dependencies:
        patterns:
          - "*"
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    target-branch: develop
    labels:
      - dependency
    commit-message:
      prefix: "[DCJ-308-docker]"
    groups:
      docker-dependencies:
        patterns:
          - "*"
