version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    target-branch: develop
    reviewers:
      - "@DataBiosphere/DUOS"
    labels:
      - dependency
    commit-message:
      prefix: "[DUOS-1740]"
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    target-branch: develop
    reviewers:
      - "@DataBiosphere/DUOS"
    labels:
      - dependency
    ignore:
      - dependency-name: broad-dsp-gcr-public/base/jre
        versions:
          - ">= 15.pre.alpine.a, < 16"
    commit-message:
      prefix: "[DUOS-1740]"
