version: 2.1

jobs:
  owasp:
    machine: true
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run:
          name: OWASP Dependency Checks
          command: mvn dependency-check:check
      - store_artifacts:
          path: target/dependency-check-report.html

workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *" # use cron syntax to set the schedule
          filters:
            branches:
              only: develop
    jobs:
      - owasp
