version: 1
update_configs:
- package_manager: "java:maven"
  directory: "/"
  update_schedule: "daily"
  target_branch: "develop"
  default_reviewers:
    - "rushtong"
    - "JVThomas"
  default_assignees:
    - "rushtong"
    - "JVThomas"
  default_labels:
    - "dependency"
  commit_message:
    prefix: "dependency"
- package_manager: docker
  directory: "/"
  update_schedule: "daily"
  target_branch: "develop"
  default_reviewers:
    - "rushtong"
  default_assignees:
    - "rushtong"
  default_labels:
    - "dependency"
  commit_message:
    prefix: "dependency"
