package org.broadinstitute.consent.http.enumeration;

public enum ClinicalTrialStatus {
  ACTIVE_NOT_RECRUITING,
  COMPLETED,
  ENROLLING_BY_INVITATION,
  NOT_YET_RECRUITING,
  RECRUITING,
  SUSPENDED,
  TERMINATED,
  WITHDRAWN,
  AVAILABLE,
  NO_LONGER_AVAILABLE,
  TEMPORARILY_NOT_AVAILABLE,
  APPROVED_FOR_MARKETING,
  WITHHELD,
  UNKNOWN
}
