version: '3.0'
services:
  consent-postgres:
    image: postgres:11.6-alpine
    logging:
      driver: none
    environment:
      - POSTGRES_USER=automation
      - POSTGRES_PASSWORD=automation
      - POSTGRES_DB=consent
    ports:
      - 5432:5432

  consent-app:
    image: consent
    logging:
      driver: none
    depends_on:
      - consent-postgres
    build:
      context: ../
      dockerfile: Dockerfile
    volumes:
      - ./consent-automation-config.yml:/opt/consent-config.yml
    ports:
      - 8000:8000
    environment:
      - CONSENT_CHANGELOG_FILE=test-data.xml
    command: ["java", "-jar", "/opt/consent.jar", "server", "/opt/consent-config.yml"]

  automation-tests:
    image: automation-test
    depends_on:
      - consent-app
    build:
      context: ./
      dockerfile: Dockerfile
