name: automation
on: [ pull_request ]

jobs:
  automation-tests:
    name: Automation Tests
    runs-on: ubuntu-latest
    steps:

      - name: Log Actor
        run: echo "${{ github.actor }}"

      # For all dependabot PRs, add a sleep time from 0-9 minutes to reduce
      # the contention on pulling repo secrets from multiple, simultaneous PRs
      - name: Calculate Sleep if Dependabot
        id: sleep
        if: github.actor == 'dependabot[bot]'
        shell: bash
        run: echo "::set-output name=minutes::$(($GITHUB_RUN_NUMBER % 10))"
      - name: Sleep if Dependabot
        if: github.actor == 'dependabot[bot]'
        uses: whatnick/wait-action@master
        with:
          time: '${{ steps.sleep.outputs.minutes }}m'

      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup paths
        run: |
          mkdir -p automation/src/test/resources/accounts
          mkdir -p automation/target

      - name: Render configs
        env:
          ADMIN: ${{ secrets.DUOS_AUTOMATION_ADMIN }}
          CHAIR: ${{ secrets.DUOS_AUTOMATION_CHAIR }}
          MEMBER: ${{ secrets.DUOS_AUTOMATION_MEMBER }}
          RESEARCHER: ${{ secrets.DUOS_AUTOMATION_RESEARCHER }}
          SIGNING_OFFICIAL: ${{ secrets.DUOS_AUTOMATION_SIGNING_OFFICIAL }}
        run: |
          echo "$ADMIN" >> ./automation/src/test/resources/accounts/duos-automation-admin.json
          echo "$CHAIR" >> ./automation/src/test/resources/accounts/duos-automation-chair.json
          echo "$MEMBER" >> ./automation/src/test/resources/accounts/duos-automation-member.json
          echo "$RESEARCHER" >> ./automation/src/test/resources/accounts/duos-automation-researcher.json
          echo "$SIGNING_OFFICIAL" >> ./automation/src/test/resources/accounts/duos-automation-signing-official.json
          ls -al ./automation/src/test/resources/accounts

      - name: Run automation tests
        run: |
          cd ./automation
          docker-compose up --abort-on-container-exit --exit-code-from automation-tests

      - name: Stop containers
        if: always()
        run: |
          cd ./automation
          docker-compose -f docker-compose.yml down
