name: automation
on: [workflow_dispatch]

jobs:
  automation-tests:
    name: Automation Tests
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:

      - name: Log Actor
        run: echo "${{ github.actor }}"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup paths
        run: |
          mkdir -p automation/src/test/resources/accounts
          mkdir -p automation/target

      - name: Render configs
        env:
          ADMIN: ${{ secrets.DUOS_AUTOMATION_ADMIN_SA }}
          CHAIR: ${{ secrets.DUOS_AUTOMATION_CHAIR_SA }}
          MEMBER: ${{ secrets.DUOS_AUTOMATION_MEMBER_SA }}
          RESEARCHER: ${{ secrets.DUOS_AUTOMATION_RESEARCHER_SA }}
          SIGNING_OFFICIAL: ${{ secrets.DUOS_AUTOMATION_SIGNING_OFFICIAL_SA }}
        run: |
          echo "$ADMIN" >> ./automation/src/test/resources/accounts/duos-automation-admin.json
          echo "$CHAIR" >> ./automation/src/test/resources/accounts/duos-automation-chair.json
          echo "$MEMBER" >> ./automation/src/test/resources/accounts/duos-automation-member.json
          echo "$RESEARCHER" >> ./automation/src/test/resources/accounts/duos-automation-researcher.json
          echo "$SIGNING_OFFICIAL" >> ./automation/src/test/resources/accounts/duos-automation-signing-official.json
          ls -al ./automation/src/test/resources/accounts

      - name: Run automation tests
        run: |
          cd ./automation
          docker-compose up --abort-on-container-exit --exit-code-from automation-tests

      - name: Stop containers
        if: always()
        run: |
          cd ./automation
          docker-compose -f docker-compose.yml down
