name: automation
on: [ pull_request ]

jobs:
  automation-tests:
    name: Automation Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup paths
        run: |
          mkdir -p automation/src/test/resources
          mkdir -p target

      - name: Render admin
        run: |
          echo ${{ secrets.DUOS_AUTOMATION_ADMIN }} >> automation/src/test/resources/duos-automation-admin.json

      - name: Render others
        run: |
          echo ${{ secrets.DUOS_AUTOMATION_CHAIR }} >> automation/src/test/resources/duos-automation-chair.json
          echo ${{ secrets.DUOS_AUTOMATION_MEMBER }} >> automation/src/test/resources/duos-automation-member.json
          echo ${{ secrets.DUOS_AUTOMATION_RESEARCHER }} >> automation/src/test/resources/duos-automation-researcher.json
          echo ${{ secrets.DUOS_AUTOMATION_SIGNING_OFFICIAL }} >> automation/src/test/resources/duos-automation-signing-official.json

      - name: Start containers
        run: |
          docker-compose -f "docker-compose-automation.yml" up -d --build

      - name: Build/Run automation tests
        run: |
          cd ./automation
          docker build -f Dockerfile -t automation-consent .
          docker run -v "${PWD}/target":/app/target --net consentautomation_default -e CONSENT_API_URL='http://consent-api:8000/' automation-consent

      - name: Stop containers
        if: always()
        run: |
          docker-compose -f "docker-compose-automation.yml" down