name: Tag, Build and Push Image

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
env:
  REGISTRY_HOST: us-central1-docker.pkg.dev
  GOOGLE_PROJECT: dsp-artifact-registry
  SERVICE_NAME: ${{ github.event.repository.name }}
jobs:
  tag-build-push:
    runs-on: ubuntu-latest
    outputs:
      sherlock-version: ${{ steps.short-sha.outputs.sha }}
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Get Short Sha
        id: short-sha
        run: echo "sha=$(git rev-parse --short=12 HEAD)" >> $GITHUB_OUTPUT
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@aa5489c8933f4cc7a4f7d45035b3b1440c9c10db'
      - name: Construct tags
        id: construct-tags
        run: |
          SHA_TAG="${REGISTRY_HOST}/${GOOGLE_PROJECT}/${SERVICE_NAME}/${SERVICE_NAME}:${SHORT_SHA}"
          ENVIRONMENT_TAG=""
          if [ "$GITHUB_EVENT" = "pull_request" ]; then
            ENVIRONMENT_TAG="${REGISTRY_HOST}/${GOOGLE_PROJECT}/${SERVICE_NAME}/${SERVICE_NAME}:pr-${SHORT_SHA}"
          elif [ "$GITHUB_EVENT" = "push" ]; then
            ENVIRONMENT_TAG="${REGISTRY_HOST}/${GOOGLE_PROJECT}/${SERVICE_NAME}/${SERVICE_NAME}:dev"
          fi
          echo "sha-tag=$SHA_TAG" >> $GITHUB_OUTPUT
          echo "environment-tag=$ENVIRONMENT_TAG" >> $GITHUB_OUTPUT
        env:
          SHORT_SHA: ${{ steps.short-sha.outputs.sha }}
          GITHUB_EVENT: ${{ github.event_name }}
      - name: Build Image
        run: |
          docker build -t "${SHA_TAG}" -t "${ENVIRONMENT_TAG}" .
        env:
          SHA_TAG: ${{ steps.construct-tags.outputs.sha-tag }}
          ENVIRONMENT_TAG: ${{ steps.construct-tags.outputs.environment-tag }}
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v3'
        with:
          # Centralized in dsp-tools-k8s; ask in #dsp-devops-champions for help troubleshooting
          token_format: 'access_token'
          workload_identity_provider: 'projects/1038484894585/locations/global/workloadIdentityPools/github-wi-pool/providers/github-wi-provider'
          service_account: 'dsp-artifact-registry-push@dsp-artifact-registry.iam.gserviceaccount.com'
      # authenticate to GAR docker repo
      - name: Docker Login
        uses: 'docker/login-action@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093'
        with:
          registry: 'us-central1-docker.pkg.dev'
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
      - name: Push Image to DSP GAR
        run: |
          gcloud auth configure-docker "$GOOGLE_PROJECT" --quiet
          docker push "${SHA_TAG}"
          docker push "${ENVIRONMENT_TAG}"
        env:
          SHA_TAG: ${{ steps.construct-tags.outputs.sha-tag }}
          ENVIRONMENT_TAG: ${{ steps.construct-tags.outputs.environment-tag }}
  report-to-sherlock:
    uses: broadinstitute/sherlock/.github/workflows/client-report-app-version.yaml@main
    needs: [ tag-build-push ]
    with:
      new-version: ${{ needs.tag-build-push.outputs.sherlock-version }}
      chart-name: 'consent'
    permissions:
      contents: 'read'
      id-token: 'write'
  set-version-in-dev:
    if: github.event_name == 'push'
    uses: broadinstitute/sherlock/.github/workflows/client-set-environment-app-version.yaml@main
    needs: [ tag-build-push, report-to-sherlock ]
    with:
      new-version: ${{ needs.tag-build-push.outputs.sherlock-version }}
      chart-name: 'consent'
      environment-name: 'dev'
    secrets:
      sync-git-token: ${{ secrets.BROADBOT_TOKEN }}
    permissions:
      id-token: 'write'
