name: Tag, Build and Push Image

on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop
env:
  REGISTRY_HOST: gcr.io
  GOOGLE_PROJECT: broad-dsp-gcr-public
  SERVICE_NAME: ${{ github.event.repository.name }}
jobs:
  tag-build-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Get Short Sha
      id: short-sha
      run: echo "::set-output name=sha::$(git rev-parse --short=12 HEAD)"
    - name: Auth to GCR
      uses: google-github-actions/setup-gcloud@v0
      with:
        version: '270.0.0'
        service_account_email: ${{ secrets.GCR_PUBLISH_EMAIL }}
        service_account_key: ${{ secrets.GCR_PUBLISH_KEY_B64 }}
    - name: Auth Docker for GCR
      run: gcloud auth configure-docker --quiet
    - name: Construct tags
      id: construct-tags
      run: |
        SHA_TAG="${REGISTRY_HOST}/${GOOGLE_PROJECT}/${SERVICE_NAME}:${{ steps.short-sha.outputs.sha }}"
        ENVIRONMENT_TAG=""
        if ${{ github.event_name == 'pull_request'}}; then
          ENVIRONMENT_TAG="${REGISTRY_HOST}/${GOOGLE_PROJECT}/${SERVICE_NAME}:pr-${{ steps.short-sha.outputs.sha }}"
        elif ${{github.event_name == 'push' }}; then
          ENVIRONMENT_TAG="${REGISTRY_HOST}/${GOOGLE_PROJECT}/${SERVICE_NAME}:dev"
        fi
        echo ::set-output name=sha-tag::$SHA_TAG
        echo ::set-output name=environment-tag::$ENVIRONMENT_TAG
    - name: Build Image
      run: |
        docker build \
        -t ${{ steps.construct-tags.outputs.sha-tag }} \
        -t ${{ steps.construct-tags.outputs.environment-tag }} \
        .
    - name: Log Github Actor
      run: echo "${{ github.actor }}"
    - name: Push Image to GCR
      if: github.actor != 'dependabot[bot]'
      run: |
        docker push ${{ steps.construct-tags.outputs.sha-tag }}
        docker push ${{ steps.construct-tags.outputs.environment-tag }}
    - name: Dispatch to terra-helmfile
      if: github.event_name == 'push'
      uses: broadinstitute/repository-dispatch@master
      with:
        token: ${{ secrets.BROADBOT_TOKEN }}
        repository: broadinstitute/terra-helmfile
        event-type: update-service
        client-payload: '{"service": "consent", "version": "${{ steps.short-sha.outputs.sha }}", "dev_only": false}'
    - name: Notify Slack
      # only notify for develop branch build
      if: github.event_name == 'push'
      uses: broadinstitute/action-slack@v3.8.0
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        status: ${{ job.status }}
        channel: "#duos-notifications"
        fields: repo,commit,author,action,eventName,ref,workflow,job,took
