name: consent-smoke-tests

on: [ pull_request ]

jobs:
  create-bee-workflow:
    strategy:
      matrix:
        terra-env: [ dev ] # what versions of apps do we use to emulate types of environments
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Wait for build to succeed
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.ref }}
          check-name: 'report-to-sherlock'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 180
      - name: Echo Consent version
        run: |
          echo '${{ needs.tag-build-push.outputs.sha-tag }}'

#      - name: dispatch to terra-github-workflows
#        uses: broadinstitute/workflow-dispatch@v3
#        with:
#          workflow: bee-create
#          repo: broadinstitute/terra-github-workflows
#          ref: refs/heads/main
#          token: ${{ secrets.BROADBOT_TOKEN}} # github token for access to kick off a job in the private repo
#          # manually recalculate b/c env context is broken https://github.com/actions/runner/issues/480
#          inputs: '{ "bee-name": "${{ github.event.repository.name }}-${{ github.run_id }}-${{ matrix.terra-env }}", "version-template": "${{ matrix.terra-env }}", "custom-version-json": "${{ needs.tag-build-push.outputs.sha-tag }}" }'
