name: Maven
on: [pull_request]
jobs:
  package:
    name: Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 25
          cache: 'maven'
      - name: Validate
        run: |
          mvn io.github.chains-project:maven-lockfile:validate -DincludeMavenPlugins=true -DallowEnvironmentalValidationFailure=true --batch-mode
      - name: Spotless Check
        run: mvn -q spotless:check --batch-mode
      - name: Package
        env:
          MAVEN_OPTS: -Dorg.slf4j.simpleLogger.defaultLogLevel=warn -Dmaven.test.skip=true -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
        run: |
          mvn -v
          mvn clean package  --batch-mode
