name: Maven
on: [pull_request]
jobs:
  package:
    name: Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5
        with:
          distribution: 'temurin'
          java-version: 25
          cache: 'maven'
      - name: Validate Maven wrapper download
        run: |
          rm -rf "${HOME}/.m2/wrapper/dists"
          ./mvnw -v --batch-mode
      - name: Spotless Check
        run: ./mvnw -q spotless:check --batch-mode
      - name: Package
        env:
          MAVEN_OPTS: -Dorg.slf4j.simpleLogger.defaultLogLevel=warn -Dmaven.test.skip=true -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
        run: |
          ./mvnw -v
          ./mvnw clean package --batch-mode
