name: OWASP
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  package:
    name: OWASP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Run Report
        run: |
          mvn -v
          mvn dependency-check:check --no-transfer-progress
      - name: Archive Report
        uses: actions/upload-artifact@v2
        with:
          name: owasp-report
          path: target/dependency-check-report.html
