name: Semgrep
on: [ pull_request ]
jobs:
  semgrep:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    name: Check
    steps:
      - uses: actions/checkout@v3
      - run: semgrep ci --config=p/findsecbugs
