name: Semgrep
on: [ pull_request ]
jobs:
  semgrep:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    name: Check
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          persist-credentials: false
      - run: semgrep ci --config=p/findsecbugs
