name: Package
on: [pull_request]
jobs:
  build:
    name: Maven Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Maven build
        run: |
          sudo apt update
          sudo apt install maven
          mvn package
