name: Trivy
on: [pull_request]
jobs:
  build:
    name: Scan for Vulnerabilities
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Maven build
        run: |
          mvn -v
          mvn package -Dmaven.test.skip=true
      - name: Build an image from Dockerfile
        run: |
          docker build -t docker.io/broadinstitute/consent:${{ github.sha }} .
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/broadinstitute/consent:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: false
          severity: 'CRITICAL'
