name: dsp-appsec-trivy
on: [pull_request]

jobs:
  appsec-trivy:
    # Parse Dockerfile and build, scan image if a "blessed" base image is not used
    name: DSP AppSec Trivy check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - uses: broadinstitute/dsp-appsec-trivy-action@c1b62b340a158930941f2ffde12831c1d1df586d # v1
